### ISSUE TITLE
Add howto for Windows 10

### ISSUE THREAD

**Issue by koppor** [marticliment/Widgets-for-UniGetUI#1]
I installed "WingetUI Widgets" from the Microsoft store, but I don't have any clue how to start them.

Do I need [8GadgetPack](https://8gadgetpack.net/) (as outlined at [giga.de](https://www.giga.de/downloads/windows-10/tipps/windows-10-gadgets-aktivieren-so-bekommt-ihr-minianwendungen-zurueck/))?

**Comment by marticliment** [comment]
Hello,

WingetUI Widgets are not compatible with Windows 10. I am sorry, this is not well documented.

You require Windows Widgets Pane in order to run WingetUI Widgets

**Comment by marticliment** [comment]
I have added it to the readme. I will upper the requirement on Microsoft Store

**Comment by marticliment** [comment]
Microsoft Store shouldn't allow anymore installation on Windows 10 devices.
