### ISSUE TITLE
Installer version 0.3 missing

### ISSUE THREAD

**Issue by tjorim** [marticliment/Widgets-for-UniGetUI#3]
Checked out the last release: https://github.com/marticliment/WingetUI-Widgets/releases/tag/0.3
I noticed there is no installer attached like previous versions.
Is the only way forward to install it from the Microsoft Store?

**Comment by marticliment** [comment]
Microsoft Store is the intended source, and installing version 0.2 should trigger Microsoft Store updates.

However, I planned to add the installer later after it passed Store Certification, but I just hand't done it yet.
