### ISSUE TITLE
Version 0.5 is unable to communicate with WingetUI

### ISSUE THREAD

**Issue by BrianG61UK** [marticliment/Widgets-for-UniGetUI#7]
Version 0.5 is unable to communicate with WingetUI.
It always says "Could not communicate with WingetUI".
WingetUI 3.0.2 itself seems to be working fine.

**Comment by marticliment** [comment]
Hello,

Can you please share your WingetUI log?

**Comment by BrianG61UK** [comment]
This one?
[WingetUI Log.txt](https://github.com/marticliment/WingetUI-Widgets/files/15224888/WingetUI.Log.txt)

**Comment by marticliment** [comment]
Please navigate to http://localhost:7058/is-running and post here the result

**Comment by BrianG61UK** [comment]
> Please navigate to http://localhost:7058/is-running and post here the result

{"status": "success"}

**Comment by Shanayara** [comment]
I'm having the same problem. Localhost gives the same success status. (I have just installed the Widgets and thus don't know if it would have worked before on my system)

**Comment by marticliment** [comment]
Please download version 0.4 from this repo and let me know if it works with it after the downgrade

**Comment by BrianG61UK** [comment]
Yes 0.4 works, while 0.5 doesn't. 
I switched back and forth between the two to confirm.

**Comment by marticliment** [comment]
Please reinstall 0.4. 
I have removed 0.5 from the microsoft store until I can figure what is happening

**Comment by marticliment** [comment]
This issue has been fixed, and I have just published version 0.6 to Microsoft Store. It should be live in 2/3 days, and then a Controlled Feature Rollout will take place. 
Then, if you want to get the update ASAP you should be able to trigger a manual update from the Microsoft Store
