### ISSUE TITLE
Widgets not showing on dev home

### ISSUE THREAD

**Issue by thealonealex** [marticliment/Widgets-for-UniGetUI#9]
Hey! I'm from windows 10 and I get this:
![image](https://github.com/marticliment/Widgets-for-UniGetUI/assets/98485800/530b307a-9cb0-40d1-aabe-a6be6fd03026)

**Comment by marticliment** [comment]
Hello,

Widgets for UniGetUI is not compatible with Windows 10.

How are you using the Widgets? Dev home was not for Windows 11 only?

**Comment by thealonealex** [comment]
> Hello,
> 
> Widgets for UniGetUI is not compatible with Windows 10.
> 
> How are you using the Widgets? Dev home was not for Windows 11 only?

I guess no? And it did let me install UniGetUI widgets

**Comment by thealonealex** [comment]
other widgets work fine
![image](https://github.com/marticliment/Widgets-for-UniGetUI/assets/98485800/83a7f9cb-dbec-4884-80d6-47d6448c6352)

**Comment by marticliment** [comment]
Can you please check which version of WingetUI Widgets you have installed?

**Comment by marticliment** [comment]
Perhaps they backported Dev Home to be compatible with W10

**Comment by thealonealex** [comment]
> Can you please check which version of WingetUI Widgets you have installed?

msstore gave me 0.2.0.0

**Comment by marticliment** [comment]
Oh, MS Store is pulling an older version.

My escuses. I will push an update allowing W10 users to install Widgets for UniGetUI

**Comment by thealonealex** [comment]
in the meanwhile I'll try to get the msix file haha
thanks

**Comment by thealonealex** [comment]
(oh well it doesn't work I'll wait for the fix haha)

**Comment by marticliment** [comment]
I have pushed an update with a lower Windows version requirement. The app should update automatically once it passes verification.

**Comment by marticliment** [comment]
You should now be able to update widgets from Microsoft Store
